pol_name = "Y1"
ndays = 30
start_day = 0
datadir = "hist_tests/"
results_hist2d = "hist2d_Y1_0_30.csv"
last_day = 2025-01-31T15:00:00.000Z
units = "arcsec"
results_hist = "hist_Y1_0_30.csv"
first_day = 2025-01-01T15:00:00.000Z

[stats]
mean_colat_err = 69.97883575617284
mean_point_err = 660.788640625
mean_long_err = 0.001001057098765432

[config_ang]
tiltang_arcmin = 0.0
wheel3ang_0_arcmin = 0.0
panang_arcmin = 0.0
wheel1ang_0_arcmin = 0.0
omegaVAXang_arcmin = 0.0
forkang_arcmin = 0.0
wheel2ang_0_arcmin = 10.0
zVAXang_arcmin = 0.0
rollang_arcmin = 0.0
