# ==========================================================
# Parameters File for StripeLine-Pointing-Simulation
# ==========================================================

# ==========================================================
# Various parameters of the simulation
[parameters]
f_sample = 50.0   # Sampling frequency of the simulation in Hz
datetime = 2025-01-01 15:00:00Z   # DateTime (separeted by a space charcater) when the simulation starts
day_duration_s = 86401.0   # Day duration in seconds, for ground coords in genpointings
datadir = "hist_tests/"   # Directory to save simulation results
units = "arcsec"   # Units for histogram making - Choose between "deg", "arcmin", "arcsec", "10 arcsec", "5 arcsec"
cleardir = false   # Clear already existing results directories - WARNING for using it with parallel
progressbar = false   # Show a progress bar during the simualtion
correct_azimuth = true # Apply the azimuth projection correction for grounds coordinates
map_save = true # Do map making process
input_map = "PySM_inputmap_nside256.fits" # Input map file
nside = 256 # NSIDE for the input map
# ==========================================================


# ==========================================================
# Configuration angles in arcsec - At least one angle must be non-zero
[config_angles]
wheel1ang_0_arcsec = 187.0
wheel2ang_0_arcsec = 300.0
wheel3ang_0_arcsec = -123.0
forkang_arcsec  = 18.0
omegaVAXang_arcsec = -40.0
zVAXang_arcsec = -16.0
panang_arcsec = 50.0
tiltang_arcsec = -176.0
rollang_arcsec =  102.0
# ==========================================================