# ==========================================================
# Parameters File for StripeLine-Pointing-Simulation
# ==========================================================


# ==========================================================
# Various parameters of the simulation
[parameters]
f_sample = 50.0   # Sampling frequency of the simulation
datetime = 2025-01-01 15:00:00Z   # Date and Time (separeted by a space charcater) when the simulation starts.
dirname = "hits_tests/"   # Directory to save simulation results
# ==========================================================


# ==========================================================
# Configuration angles - At least one angle must be non-zero
[config_angles]
wheel1ang_0_arcmin = 0.0
wheel2ang_0_arcmin = 120.0
wheel3ang_0_arcmin = 0.0
forkang_arcmin  = 0.0
omegaVAXang_arcmin = 0.0
zVAXang_arcmin = 0.0
panang_arcmin = 0.0
tiltang_arcmin = 0.0
rollang_arcmin =  0.0
# ==========================================================