long_c_eq = -14.0
ndays = 1
polarimeter = "I0"
colat_c_gr = 176.0
start_day = 0
r_scan_eq = 235.5
datadir = "hist_tests/"
results_hist2d = "hist2d_I0_0_1.csv"
last_day = 2025-01-02T15:00:00.000Z
colat_c_eq = 0.0
long_c_gr = 359.0
r_scan_gr = 30.0
units = "arcsec"
results_hist = "hist_I0_0_1.csv"
first_day = 2025-01-01T15:00:00.000Z

[config_ang]
tiltang_arcsec = -176.0
wheel1ang_0_arcsec = 187.0
wheel3ang_0_arcsec = -123.0
zVAXang_arcsec = -16.0
wheel2ang_0_arcsec = 0.0
rollang_arcsec = 102.0
panang_arcsec = 50.0
forkang_arcsec = 18.0
omegaVAXang_arcsec = -40.0
