units = "10 arcsec"
results_hist2d = "hist2d_V4_3_7.csv"
datadir = "hist_tests/"
last_day = 2025-01-08T15:00:00.000Z
results_hist = "hist_V4_3_7.csv"
first_day = 2025-01-04T15:00:00.000Z
ndays = 4
polarimeter = "V4"
start_day = 3

[config_ang]
tiltang_arcmin = 0.0
wheel3ang_0_arcmin = 0.0
panang_arcmin = 0.0
wheel1ang_0_arcmin = 0.0
omegaVAXang_arcmin = 0.0
forkang_arcmin = 10.0
wheel2ang_0_arcmin = 10.0
zVAXang_arcmin = 10.0
rollang_arcmin = 0.0
