units = "10 arcsec"
results_hist2d = "hist2d_V4_4_5.csv"
datadir = "hist_tests/"
last_day = 2025-01-06T15:00:00.000Z
results_hist = "hist_V4_4_5.csv"
first_day = 2025-01-05T15:00:00.000Z
ndays = 1
polarimeter = "V4"
start_day = 4

[config_ang]
tiltang_arcmin = 0.0
wheel3ang_0_arcmin = 0.0
panang_arcmin = 0.0
wheel1ang_0_arcmin = 0.0
omegaVAXang_arcmin = 0.0
forkang_arcmin = 10.0
wheel2ang_0_arcmin = 10.0
zVAXang_arcmin = 10.0
rollang_arcmin = 0.0
